// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Instance",
    group: "compute",
    properties: ({}) => ({
      name: "web-server",
      machineType: "e2-micro",
      metadata: {
        items: [
          {
            key: "enable-oslogin",
            value: "True",
          },
        ],
      },
      sourceImage:
        "projects/debian-cloud/global/images/debian-12-bookworm-v20240815",
    }),
  },
];
