// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Address",
    group: "compute",
    properties: ({}) => ({
      name: "ip-webserver",
      description: "Managed By GruCloud",
      networkTier: "PREMIUM",
      addressType: "EXTERNAL",
    }),
  },
  {
    type: "Disk",
    group: "compute",
    properties: ({}) => ({
      name: "disk",
      sizeGb: "20",
      type: "pd-standard",
    }),
  },
  {
    type: "Firewall",
    group: "compute",
    properties: ({}) => ({
      name: "firewall-22-80-433",
      description: "Managed By GruCloud",
      priority: 1000,
      allowed: [
        {
          IPProtocol: "tcp",
          ports: ["22", "80", "433"],
        },
      ],
      direction: "INGRESS",
      logConfig: {
        enable: false,
      },
    }),
  },
  {
    type: "Firewall",
    group: "compute",
    properties: ({}) => ({
      name: "firewall-icmp",
      description: "Managed By GruCloud",
      priority: 1000,
      allowed: [
        {
          IPProtocol: "icmp",
        },
      ],
      direction: "INGRESS",
      logConfig: {
        enable: false,
      },
    }),
  },
  {
    type: "Instance",
    group: "compute",
    properties: ({}) => ({
      name: "webserver",
      machineType: "e2-micro",
      metadata: {
        items: [
          {
            key: "enable-oslogin",
            value: "True",
          },
        ],
      },
      sourceImage:
        "projects/debian-cloud/global/images/debian-12-bookworm-v20240815",
    }),
    dependencies: ({}) => ({
      ip: "ip-webserver",
      disks: ["disk"],
    }),
  },
  {
    type: "ServiceAccount",
    group: "iam",
    properties: ({}) => ({
      accountId: "sa-test-vm",
      serviceAccount: {
        displayName: "SA dev",
        description: "Managed By GruCloud",
      },
    }),
  },
];
