// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Firewall",
    group: "compute",
    properties: ({}) => ({
      name: "firewall",
      description: "Managed By GruCloud",
      priority: 1000,
      allowed: [
        {
          IPProtocol: "tcp",
          ports: ["22", "80", "433"],
        },
      ],
      direction: "INGRESS",
      logConfig: {
        enable: false,
      },
    }),
    dependencies: ({}) => ({
      network: "vpc",
    }),
  },
  {
    type: "Instance",
    group: "compute",
    properties: ({}) => ({
      name: "db",
      machineType: "e2-micro",
      metadata: {
        items: [
          {
            key: "enable-oslogin",
            value: "True",
          },
        ],
      },
      sourceImage:
        "projects/debian-cloud/global/images/debian-12-bookworm-v20240815",
    }),
    dependencies: ({}) => ({
      subNetwork: "subnetwork",
    }),
  },
  {
    type: "Network",
    group: "compute",
    properties: ({}) => ({
      description: "Managed By GruCloud",
      autoCreateSubnetworks: false,
      name: "vpc",
      routingConfig: {
        routingMode: "REGIONAL",
      },
    }),
  },
  {
    type: "Subnetwork",
    group: "compute",
    properties: ({}) => ({
      name: "subnetwork",
      ipCidrRange: "10.164.0.0/20",
    }),
    dependencies: ({}) => ({
      network: "vpc",
    }),
  },
];
